### ISSUE TITLE
[Question] This looks amazing!

### ISSUE THREAD

**Issue by Vip3rLi0n** [WebTheDev/TicketBot#16]
Hi, I have a few questions.
- How fast does the bot respond when under pressure? (Say, 200-500 tickets)
- Is there a function where I can toggle auto transcript without needing to click the transcript button? I hope there is, so I can reduce the button on Options
- Will there a function in the future where you will make a basic webpage functionality to manage the bot function? I'm very interested with this idea.
- Will you add a function to let it use MariaDB in the future?

Thanks for developing the bot, it looks really neat. The code are also easy to understand.

**Comment by WebTheDev** [comment]
Hi there!
1. The bot can handle a max of 100 tickets at a time before it starts to throw errors. (50 in the active category and 50 in the onhold category.)

2. The pinned message in the channel the bot creates has a "close ticket" button that has the same functionality the transcript button.

3. I'm not looking to add webpage functionality right now but I am working on a debug feature.

4. I'm not planning to add a MariaDB function right now.

I appreciate your kind words =)
