### ISSUE TITLE
HttpException

### ISSUE THREAD

**Issue by CMAULTOP** [WebTheDev/TicketBot#17]
And why is it necessary to make a separate response with HttpException for each response?

**Comment by WebTheDev** [comment]
Hi there,

Discord embeds will sometimes not work properly or embed limits are reached unintentionally, and instead of the bot throwing an uncaught error with no response. The HttpException allows for the bot to still be functional without an embedded response.

**Comment by CMAULTOP** [comment]
Are these embedding restrictions frequent or rare? Or does it even make sense to leave these alternative answers?

**Comment by WebTheDev** [comment]
They are a rarity but are still nice to have when these errors occur.
