### ISSUE TITLE
Issue with the ticket bot reconnecting too many times 

### ISSUE THREAD

**Issue by mushy420** [WebTheDev/TicketBot#19]
“ It appears your bot, ticket tool helper, has connected to Discord more than 1000 times within a short time period. Since this kind of behavior is usually a result of a bug we have gone ahead and reset your bot's token. “

Any reason this may happen?

**Comment by WebTheDev** [comment]
Hi there,

Please ensure that the bot is running on a stable internet connection.

**Comment by mushy420** [comment]
Hi there, I use bot-hosting.net and i’m on their premium node ensuring it’s running smoothly

maybe their node just went down and caused this? Hopefully discord wouldn’t ban my account for such bug as it got me worried 😅
