### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by mushy420** [WebTheDev/TicketBot#21]
Saw this error in my console, also doing screenshots as my host provider doesn’t support of copying the console sadly. + my console has a limited amount of space so this is as far back on the error i could go this may not be the start of the error and may be a incomplete error.

https://media.discordapp.net/attachments/1170125527772835921/1201868509118730360/image0.jpg?ex=65cb6246&is=65b8ed46&hm=fd268df6c57f2301b63c1ef515f08d255d0b9aa92078964ab4dc19fc1120c9d9&

https://media.discordapp.net/attachments/1170125527772835921/1201868982534295622/image0.jpg?ex=65cb62b7&is=65b8edb7&hm=1c49755547d03699fc2ef3eee12f67bb0fb37593f7fd2bd02461a8f90e614520&

https://media.discordapp.net/attachments/1170125527772835921/1201869403294290010/image0.jpg?ex=65cb631b&is=65b8ee1b&hm=46eb5f6ada810b808848d8503c4ed40697af3ae34e5ebdcbc3ed6a8581e7c134&

Overall, the bot is still functioning not entirely sure what this is but noticed this when doing my usual check on my console for errors.

**Comment by WebTheDev** [comment]
Hi there, 

Are you still able to make new tickets as of this moment?

**Comment by mushy420** [comment]
> Hi there,
> 
> Are you still able to make new tickets as of this moment?

Hi, yes just tested this right now and the create ticket and close ticket is working.
