### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by smdev58** [WebTheDev/TicketBot#27]
unable to create ticket
![Екранна снимка 2024-10-28 203844](https://github.com/user-attachments/assets/baac98d0-f8ef-4e28-b271-82e42e6dd32b)
![Екранна снимка 2](https://github.com/user-attachments/assets/61b6029c-aff0-4b94-a27c-ce74c8dbb1f6)

**Comment by bom123a** [comment]
@WebTheDev

**Comment by smdev58** [comment]
@WebTheDev

**Comment by WebTheDev** [comment]
Hi there,
Most of the time non type errors are config related or permission related. Since that error means that the bot tried to pull some information however was unsuccessful. Given that I have another issue open with a similar issue I will try to replicate.

**Comment by smdev58** [comment]
ок

**Comment by bom123a** [comment]
@WebTheDev Have I set it up correctly?
![11111](https://github.com/user-attachments/assets/05a6b74a-0387-4213-85b3-cbc180d43242)
![222222](https://github.com/user-attachments/assets/6550baca-51d7-46b2-9946-05bc47eacbfe)
![333333](https://github.com/user-attachments/assets/e5644d18-e3eb-46aa-a165-28c270b733a6)

**Comment by bom123a** [comment]
@WebTheDev

**Comment by smdev58** [comment]
@WebTheDev What happened Did you understand the error?

**Comment by WebTheDev** [comment]
@bom123a 
In your second screenshot, try removing the `, 0000000000` part for your roles that can access certain discord channels.
